### PR TITLE
Add iwconfig, wpa_supplicant for wireless

### PR DESCRIPTION
**Pull request by ibuildthecloud**

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@ibuildthecloud is there are reason why you havn't merged this?

**Comment by ibuildthecloud** [comment]
@SvenDowideit Nope, I think we can do it now.  But it will require some scripting or development in rancheros netconf to actually setup wifi

**Comment by SvenDowideit** [comment]
and for that: 

```
!/bin/sh

if [ -z "$WPA_DEVICE" ] || [ -z "$WPA_ESSID" ] || [ -z "$WPA_PASSPHRASE" ]; then
    echo WPA_DEVICE, WPA_ESSID, WPA_PASSPHRASE must be set
    exit 0
fi

ip link set dev $WPA_DEVICE up
iwconfig $WPA_DEVICE essid $WPA_ESSID
echo "$WPA_PASSPHRASE" | wpa_passphrase $WPA_ESSID > wpa.conf
exec wpa_supplicant -Dwext -i${WPA_DEVICE} -c ./wpa.conf
```

I wonder where we'll document that :)

**Comment by joshwget** [comment]
This script seems pretty simple. I don't think it would be too difficult to add native cloud-config parameters for this type of functionality.

**Comment by SvenDowideit** [comment]
I'd totally prefer a service container..

**Comment by ibuildthecloud** [comment]
@joshwget not too sure how robust it is, but it give the most basic functionality.  Probably worth looking at how ifup or systemd-networkd handle wifi.

**Comment by SvenDowideit** [comment]
merged, as I'm going to be rebuilding os-base today as it is :)

**Pull request merged**
