### PR TITLE
cryptsetup (LUKS), LVM2, BTRFS, XFS, NBD, gptdisk, 

### PR DESCRIPTION
**Pull request by berezins**
Needed to switch back to GLIBC (uClibc gave 'segfault error 6 in libdevmapper' on cryptsetup open). 

Using in production with v0.4.5 Rancher OS since about 5 months. Completely diskless statless iPXE booted, considering physical machine just like a pool of resources with just docker containers and volumes on encrypted BTRFS disk. Now I got necessity to have Rancher OS state partition on the same encrypted BTRFS as subvolume. And gonna to check at the end of rancher.bootstrap if rancher.state.dev specified but not mounted. And if so then to bring temporary shell via console and ssh (for possible remote unlocking of LUKS encrypted via cryptsetup or helper command). I am gonna to implement it within existing rancher.bootstrap.bootstrap service (within os-bootstrap image) or to add new service (with new image also os-base based) to same rancher.bootstrap service set. This service will complete/exit to continue normal boot sequence once special helper command (e.g. continue_boot) will be called there in shell (by admin or e.g. by remote script to simple unlock LUKS encrypted state partition or to push some remote binary and perform some more complex security checks, checksummig etc before unlocking - up to admin inventiveness). There could be implemented few another helper commands like unlock (which would automate process of unlocking state partition by checking whether it is specified by device path or by label and if by label then to scan and start mdadm and lvm devices first and then to check all block devices if any is LUKS encrypted and if so then to ask for passphrase. And another to initiate NBD device (in case of totally diskless machine, e.g. like scaleway.com real case I use btw, but without rancher for a while and bringing  rancher os to there would be a big win IMO BTW). Plus all flexibility of buildroot environment up to admin, so configuration and unlocking of any complexity can be performed by admin or automated remote script.
And actually any other arbitrary storage related checks/configs/unlocks can be pushed as extra service to rancher.bootstrap service set and based on same os-bootstrap (or our new service and image specially for it), via cloud-config specified in kernel arg or on OEM partition or so. Freedom and flexibility and at the same time simplicity are absolute incomparable with other distros

Please let me know in case of any advice or any other job done in this direction already.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
We'd like not to switch to glibc - and we're not really sure of the side effects of adding this to the default distro. We need an idea of what i'll take to test this kind of thing for the future :/

**Comment by berezins** [comment]
> We'd like not to switch to glibc

Reasons? Just a quick higlight please.

> and we're not really sure of the side effects of adding this to the default distro

In't glibc much more mature and tested with much more kernels and software since used in majority of general purpose linux distros (where most of software is really used and tested)? So far I know uClibc is quite younger and used primarily in embeddted systems for its smaller size. Please correct me if I am wrong. As proof of my opinion - a simple fact that cryptsetup does not work with uClibc and no working solution I have found for a while.

From the point of maximal reobustness, stability and eliminating of side effects - I would even switch os-base from buildroot to alpine which is also very tiny based on musl but where much more software and kernel modules/features are well tested/proven. At the same time it would give much more opportnnities for end users to customize management console and even initrd image keeping it tiny without switching to ubuntu/debian/centos console. In this case IMO, we would get best from both - your unique idea to use docker as actually first class sitizen on top of kernel and from already using of quite matures, secure, well tested and proven very compact minimalistic distro. If I will not hear from you weight reasons agains alpine in our case - I will find some time to make test build replacing buildroot with it and will see if it will pass all current tests or will create any issues. If none - I will try to switch to it in my production.

And another problems of uClibc and buildroot at all is devicemapper is impossible to be used as docker storage driver for containers in Rancher OS due of lack of udev sync support in statically linked docker (tested by me personally and confirmed in official docker resources). And while it is potentially possible to create docker buildroot package to be built dynamically together with os-base and included in it (just not sure how easy implementable and then supported and tested it), I am not sure if somebody built docker against uclibc and more that well tested it and even more used it in production. At the same time alpine has dynamically linked agains musl docker package already quite well tested and proven so with using alpine as os-base - should solve all above problems (if you did not try it already and did not get another expirience of course).

And finally let me remind you that convoy uses devicemapper at the only option for a while for production driver taking full advantage of snapshotting technolog. I even considered to slightly modify convoy to use lvm managed thinpool for this as an option and then to setup two self growing thin pools  - one usded by docker itself for containers and another by convoy for volumes which would allow to use storage space quite effectively and at the same time giving of advantages of dm snapshotting and convoy backuping of them. But throwing away this idea for a while once realized above problem with statically linked docker

**Comment by berezins** [comment]
#31

**Comment by berezins** [comment]
Now cryptsetup/LUKS with SSH remote unlock for state partion is fully supported in [my fork](https://github.com/tetatetit/os) including LVM, BTRFS, XFS, NBD and works in my production

**Comment by SvenDowideit** [comment]
I'm presuming that to get it all working, we'd need to merge some version of your `tetatetit/os` master branch?

we're not ignoring your change, its just a large amount to digest and decide on :/

**Comment by berezins** [comment]
Just made 2 separate PRs to rancher/os to get all this consistent and fully working, just as #joshwget adviced to split my initial big PR. I hope it will simplify your decision making process :). Just stating that all of this except NBD working perfectly in my production, no issues so far. And I that tried to be extremely careful to make changes to do not affect anything else

**Comment by berezins** [comment]
Also I plan to make test branch using alpine instead os-base with included all above plus lvm thin, iSCSI and ZFS out of the box. This should make Rancher OS deployment and storage options even more advanced then in so mature distros like Ubuntu, Fedora, openSUSE, not even saying about CoreOS. Also once there features will be inlcuded in your upstream repo - I'll try to convince Scaleway.com to include Rancher OS as one of their default images which should open there possibility of all these feautres which are unavailable otherwise on their service even with custom image (due of only network boot and only storage as NBD). So Rancher OS the only way to enable all these features without chaning their architecture

**Pull request closed without merging**
